version: "3"
services:
  api:
    depends_on:
      - mail

  nginx:
    ports:
      - "80"
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME:-test}.tardisbank_nginx
      - traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME:-test}.tardisbank.net
      - traefik.docker.network=web
      - traefik.port=80

  mail:
    container_name: ${COMPOSE_PROJECT_NAME:-test}_tardis_bank_smtp
    image: namshi/smtp
    expose:
      - "25"
    labels:
      - traefik.enable=false
